Try without installing cloudsmith/install-cli

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -99,23 +99,23 @@ commands:
 #                    steps:
 #                    - cloudsmith/ensure-api-key
 #                    - cloudsmith/install-cli
-                - when:
-                    condition: <<parameters.DEPLOY-USE-ORB>>
-                    steps:
-                    - run:
-                        command: |
-                            if [[ $(command -v cloudsmith) == "" ]]; then
-                                export PIP=$(which pip pip3 | head -1)
-                                if [[ -n $PIP ]]; then
-                                    $PIP install cloudsmith-cli --upgrade --user
-                                else
-                                    echo "Unable to install Cloudsmith CLI. Please install pip."
-                                    exit 1
-                                fi
-                            else
-                                echo "Cloudsmith CLI is already installed."
-                            fi
-                        name: Install Cloudsmith CLI
+#                - when:
+#                    condition: <<parameters.DEPLOY-USE-ORB>>
+#                    steps:
+#                    - run:
+#                        command: |
+#                            if [[ $(command -v cloudsmith) == "" ]]; then
+#                                export PIP=$(which pip pip3 | head -1)
+#                                if [[ -n $PIP ]]; then
+#                                    $PIP install cloudsmith-cli --upgrade --user
+#                                else
+#                                    echo "Unable to install Cloudsmith CLI. Please install pip."
+#                                    exit 1
+#                                fi
+#                            else
+#                                echo "Cloudsmith CLI is already installed."
+#                            fi
+#                        name: Install Cloudsmith CLI
                 - run: bash ci/cloudsmith-upload.sh
 
     # if you want to use a local proxy add Acquire::http::Proxy \"http://192.168.1.1:3142\"; to a file called circleci-cache/apt-proxy. This will require
@@ -174,7 +174,6 @@ jobs:
         - OCPN_TARGET: macos
         - CMAKE_BUILD_PARALLEL_LEVEL: 2
         - WX_VER: 32
-        - install-python: true
         steps:
         - checkout
         - run: sudo chmod go+w /usr/local
